steps:
  - name: 'maven:3.8.4-openjdk-17-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mvn package -DskipTests
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fetch-app', '.']
images: ['gcr.io/$PROJECT_ID/fetch-app']
